# Configuracao Nixpacks para Cotacao Hapvida

[phases.setup]
nixPkgs = ["google-chrome", "chromedriver", "chromium"]
aptPkgs = ["chromium", "chromium-driver", "libnss3", "libatk-bridge2.0-0", "libdrm2", "libxkbcommon0", "libgbm1"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
PYTHONUNBUFFERED = "1"
DISPLAY = ":99"

[start]
cmd = "python app_cotacao.py"
