# Configuracao Nixpacks para Cotacao Hapvida

[phases.setup]
nixPkgs = ["chromium", "chromedriver"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
PYTHONUNBUFFERED = "1"

[start]
cmd = "python app_cotacao.py"
